=== Soe18/SoChat_Server/SoChat_Server-master/DatabaseChat/DBchat.dtd
<!ELEMENT chatdb (listautenti,listachat)>
<!ELEMENT listautenti (user*)>
<!ELEMENT listachat (chat*)>
<!ELEMENT user (nickName,password)>
<!ELEMENT nickName (#PCDATA)>
<!ELEMENT password (#PCDATA)>
<!ELEMENT chat (ChatMessage*)>
<!ATTLIST chat id ID #REQUIRED>
<!ELEMENT ChatMessage (Content,Sender,Receiver)>
<!ELEMENT Content (#PCDATA)>
<!ELEMENT Sender (#PCDATA)>
<!ELEMENT Receiver (#PCDATA)>

=== Soe18/SoChat_Server/SoChat_Server-master/DatabaseChat/DBchat.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE chatdb SYSTEM "DBchat.dtd">
<chatdb>
    <listautenti>
        <user>
            <nickName></nickName>
            <password></password>
        </user>
        <user>
            <nickName></nickName>
            <password></password>
        </user>
    </listautenti>
    <listachat>
        <chat id="">
            <ChatMessage>
                <Content></Content>
                <Sender></Sender>
                <Receiver></Receiver>
            </ChatMessage>
            <ChatMessage>
                <Content></Content>
                <Sender></Sender>
                <Receiver></Receiver>
            </ChatMessage>
            <ChatMessage>
                <Content></Content>
                <Sender></Sender>
                <Receiver></Receiver>
            </ChatMessage>
            <ChatMessage>
                <Content></Content>
                <Sender></Sender>
                <Receiver></Receiver>
            </ChatMessage>
            <ChatMessage>
                <Content></Content>
                <Sender></Sender>
                <Receiver></Receiver>
            </ChatMessage>
            <ChatMessage>
                <Content></Content>
                <Sender></Sender>
                <Receiver></Receiver>
            </ChatMessage>
            <ChatMessage>
                <Content></Content>
                <Sender></Sender>
                <Receiver></Receiver>
            </ChatMessage>
            <ChatMessage>
                <Content></Content>
                <Sender></Sender>
                <Receiver></Receiver>
            </ChatMessage>
            <ChatMessage>
                <Content></Content>
                <Sender></Sender>
                <Receiver></Receiver>
            </ChatMessage>
            <ChatMessage>
                <Content></Content>
                <Sender></Sender>
                <Receiver></Receiver>
            </ChatMessage>
            <ChatMessage>
                <Content></Content>
                <Sender></Sender>
                <Receiver></Receiver>
            </ChatMessage>
            <ChatMessage>
                <Content></Content>
                <Sender></Sender>
                <Receiver></Receiver>
            </ChatMessage>
        </chat>
    </listachat>
</chatdb>
